#+SETUPFILE: "~/org/personal-web-site/_org-setupfiles/level-1.org"
#+STARTUP: showall

#+COMMENT: C-c C-e P p
#+TITLE: Living Better


* Introduction

Everyone wants to improve, whether its by getting rid of bad habits,
creating some new habits, improving their routine, being more
productive, eating healthier, being healthier, etc.  That's what I'm
trying to do here.  Most of this is copied/stolen/borrowed, whatever
term you want to use for it, from other web sites.  I have not changed
the content, just did some formating changes in order to make it work
better on my website.

* Mood Boosters

You are what you eat, and when youâre stressed out or
depressed, you want junk food. So what does that make you? When your
emotions drive you to the cupboard, youâre not satisfying
hunger, youâre feeding your mood. The more garbage you feed
it, the more you want, and so the vicious cycle of eating all the
wrong things begins.

A study published in the Journal of Clinical Psychology: Science and
Practice recently found a link between obesity and depression, due to
the hormones and physiological changes that occur in the immune system
when depression sets in. The findings show people who are obese may be
more susceptible to depression, and that people who are depressed are
more likely to become obese. And so it does.

So how can you help break this link? Start by eating the right
foods. A study out of Pennsylvania State University found that eating
âcomfort foodsâ heavy in fat, sugar, salt and carbs
actually lowered the mood after being eaten, only giving a small
positive effect during the meal. Skip the âtreatsâ and
try adding some of these 10 mood busting foods to your diet. These
foods are proven to keep your energy up so you can better handle
lifeâs major stresses.

** Quinoa

Why it helps: Quinoa is a complex carbohydrate and a complete protein,
which keeps your blood sugar â and your energy levels
â steady. This helps to prevent blood sugar spikes, which can
make you irritable and unfocused. Also, itâs now widely
available in most grocery stores completely unprocessed. Plus
itâs gluten-free, so itâs great for people have
allergies to gluten or other carbs.

** Wheat Germ

Why it helps: Guess what they take out of wheat when they process it?
All the nutrients of wheat. Two tablespoons of wheat germ has 4 grams
of protein, 2 grams of fiber, low sugars and only 60 calories.  This
is better than some nutrient powders. You can mix it into all kinds of
recipes, like oatmeal, fruit or even simple salads. Some people even
use it as an ice cream topping!

** Amaranth

Why it helps: Like Quinoa, amaranth is known as an âancient
grain,â a complex carbohydrate thatâs packed with
protein and fiber, and is also gluten free. Amaranth is also a great
source of vitamin B6, a B-complex vitamin essential to mental and
emotional well being. B6 is not produced by our bodies, and is a
vitamin we need to get from our diet. Plus,  amaranth has even been
known to prevent grey hairs!

** Collard Greens

Why it helps: Collards are high in vitamin k and magnesium. One study
by the The National Institute of Health found that people with
magnesium deficiency had reduced levels of serotonin, a mood-calming
neurotransmitter. Just one cup of cooked collards has 35% of your
daily need for magnesium. Toss some into your pasta, or mix up with
other greens in a salad.

** Walnuts

Why it helps: While you may think of Omega-3 fatty acids as something
you get from fish (and youâre right) you can also get it from
walnuts. These fatty acids are great for your health, and a deficit of
these acids has been linked to depression in a study published by
Dr. Alan C Logan. A study also found that people who do not eat fish
regularly may be at higher risk for depression.

** Popcorn (air-popped)

Why it helps: Popcorn is a carb-rich food with a low glycemic index,
which can lead to holding on to serotonin levels, which in turn help
level out your mood. Popcorn can be considered a complex
carb. HOWEVER, as soon as you add sugar, salt, or oil, any benefit you
can claim from popcorn is completely cancelled out. Air-popped popcorn
with a sprinkling of spices and little to no salt is the best way to
have popcorn as a snack.

** Cottage Cheese

Why it helps: When you think of tryptophan you tend to think of
turkey, but cottage cheese is actually a great source of the amino
acid, which is linked to the mood-boosting neuro-chemical
Serotonin. Serotonin plays a role in depression, concentration and
obesity, and low levels of serotonin in the brain make it difficult to
deal with stress. The tryptophan in cottage cheese, help promote
relaxation and can help boost your mood.

** Bananas

Why it helps: Like collards, bananas give you the benefits of being
backed with magnesium and B6, but also have potassium. Potassium helps
your  heart, kidneys, muscles and gastrointestinal track work
properly. A study in the British Journal of Nutrition found that
high-potassium diets helped relieve depression symptoms and muscle
tension in its participants.

** Probiotic Yogurt

Why it helps: Your body is full of bacteria that help it function, and
probiotics help cultivate this healthy bacteria in your digestive
track. Probiotics yogurt contains the bacteria lactobacillus
rhamnosus,a natural culture that most people have. In a study from
University College in Cork, Ireland, could a  link between
lactobacillus rhamnosus and anxiety levels in their tests on
mice. Another small study also found that yogurt could help women
suffering from PMS related depression and irritability.

* Morning things to do

** Exercise
Iâve said it once, Iâll say it again. Most people that
work out daily, work out in the morning. Whether itâs a
morning yoga session or a trip to the gym, exercising before work
gives you a boost of energy for the day and that deserved sense of
accomplishment. Anyone can tackle a pile of paperwork after 200 ab
reps! Morning workouts also eliminate the possibility of flaking out
on your cardio after a long day at work. Even if you arenât
bright eyed and bushy tailed at the thought of a 5 am jog, try waking
up 15 minutes early for a quick bedside set of pushups or
stretching. Itâll help wake up your body, and prep you for
your day. 

** Map Out Your Day
Maximize your potential by mapping out your schedule for the day, as
well as your goals and to dos. The morning is a good time for this as
it is often one of the only quiet times a person gets throughout the
day. The early hours foster easier reflection that helps when
prioritizing your activities. They also allow for uninterrupted
problem solving when trying to fit everything into your
timetable. While scheduling, donât forget about your mental
health. Plan a 10 minute break after that stressful meeting for a
quick walk around the block or a moment of meditation at your
desk. Trying to eat healthy? Schedule a small window in the evening to
pack a few nutritious snacks to bring to work the next day. 

** Eat a Healthy Breakfast
We all know that rush out the door with a cup of coffee and an empty
stomach feeling. You sit down at your desk, and youâre already
wondering how early that taco truck sets up camp outside your
office. No good. Take that extra time in the morning to fuel your body
for the tasks ahead of it. It will help keep your mind on
whatâs at hand and not your growling stomach. Not only is
breakfast good for your physical health, it is also a good time to
connect socially. Even five minutes of talking with your kids or
spouse while eating a quick bowl of oatmeal can boost your spirits
before heading out the door.

** Visualization
These days we talk about our physical health ad nauseam, but sometimes
our mental health gets overlooked. The morning is the perfect time to
spend some quiet time inside your mind meditating or visualizing. Take
a moment to visualize your day ahead of you, focusing on the successes
you will have. Even just a minute of visualization and positive
thinking can help improve your mood and outlook on your work load for
the day. 

** Make Your Day Top Heavy
We all have that one item on our to do list that we dread. It looms
over you all day (or week) until you finally suck it up and do it
after much procrastination. Hereâs an easy tip to save
yourself the stress â do that least desirable task on your
list first. Instead of anticipating the unpleasantness of it from
first coffee through your lunch break, get it out of the way. The
morning is the time when you are (generally) more well rested and your
energy level is up. Therefore, you are more well equipped to handle
more difficult projects. And look at it this way, your day will get
progressively easier, not the other way around. By the time your work
day is ending, youâre winding down with easier to dos and
heading into your free time more relaxed. Success!

* Starting the work day

** Arrive on time
This may be obvious to most peopleâbut some donât
realize that showing up late can not only leave a bad impression, but
also throw off your entire day. âGetting in on time or a
little early helps your mindset for the day and helps promote a
feeling of accomplishment,â Taylor says. 

** Take a deep breath
âLiterally,â says Michael Kerr, an international
business speaker, author and president of Humor at Work. âAnd
do something to focus in on the here and now.â Many people
come into work harried because they donât leave enough time at
home to deal with âhome stuff,â he says, âand
then theyâve barely survived another horrendously stressful
commute, and then they dive into the madness.â Slowing down,
taking a moment to pause, and creating a routine around centering
yourself can work wonders, he adds.


Michael âDr. Woodyâ Woodward, PhD, organizational
psychologist and author of The YOU Plan, says after the deep breath,
give yourself a few minutes to meditate and get settled
in.âThis is a good way to set the tone of the day,â he
says. âDonât allow yourself to be bum rushed by
frantic co-workers lost in their own confusion. Itâs not
unusual to wake up to a long backlog of e-mails just screaming for
your attention. The challenge is taking a moment for yourself before
diving head first into your day.â

Woodward says he has worked with executives who meditate 10 minutes
every morning before they even think of looking at an e-mail or taking
a call. âThere is a tremendous power in mediation when it
comes to settling your mind. Starting off your day right is really
about setting your own tone and meditation is a great way to begin.â

** Eat a proper breakfast
âBreakfast truly is the most important meal of the day to help
us down the path of not only being more physically fit, but also to
have the mental energy needed to tackle your workday,â Kerr
says. 

** Start each day with a clean slate
You may have to attend to projects or discussions that rolled over
from the previous afternoonâbut try to treat each day as a
fresh one, says David Shindler, founder of The Employability Hub and
author of Learning to Leap. âLeave any crap from yesterday
behind, tap into whatâs happening at the outset of the day,
get organized and ready or hit the ground running, if thatâs
what is needed,â he says. 

** Donât be moody
Youâll want to pay attention to your mood and be aware of its
effect on others. âFirst and last thing in the day is when
emotional intelligence can have the greatest impact,â Shindler
says. So if youâre not a âmorning person,â try
to suck it up and have a positive attitude when you arrive at the
office. Grab a second or third cup of coffee, if thatâs what
it takes. 

Kerr agrees. âYour first hour at work can set your
âattitude barometerâ for the rest of the day, so from
a purely emotional point of view, I think itâs an important
part of the day,â he says. âOne morning grump can
infect an entire team and put everyone on the wrong footing.â

** Organize your day
The first hour of the work day is the best time to assess priorities
and to focus on what you absolutely need to accomplish, Kerr
says. âToo many people get distracted first thing in the
morning with unimportant activities such as diving right into their
morass of e-mail, when there may be a whole host of more important
issues that need dealing with.â Make a to-do list, or update
the one you made the previous day, and try to stick to it. However, if
your boss has an urgent need, then itâs OK re-shuffle your
priorities within reason, Taylor adds. 

Anita Attridge, a career and executive coach with the Five
OâClock Club, a career coaching organization, says when you
prepare your morning to-do list, determine what must be done today and
what can be completed tomorrow, and prioritize
accordingly. âAlso determine your peak working time and plan
your schedule accordingly,â she says. âUse your peak
time each morning to do the most important tasks.â


** Be present
Even if youâre not a morning person, you need to be awake when
you get the office. Especially if youâre in a leadership
position, itâs critical to be present, mentally and
physically, and to communicate. âOne of the biggest office pet
peeves I hear from employees is about how their immediate supervisor
just blows by them in the morning without so much as a smile,â
Kerr says. âTaking the time to connect with your team members
is essential, and doing the seemingly small thingsâmaking eye
contact,  smiling, asking them about their night,  and checking in on
what they may need help withâhelps you as a leader take the
pulse of the team, and helps set the tone for all the
employees.â 

** Check in with your colleagues
âA quick 5 to 10 minute team huddle can also be an effective
way for many people to start their day,â Kerr says. Make it a
short meeting, with no chairs, have everyone share their top goal for
the day, and share any critical information the rest of the team
absolutely needs to know, he says. âDoing the huddles helps
people focus and more importantly, connects everyone with the
team. And by sharing your goals for the day publicly, the odds of
achieving them rise substantially.â 

** Organize your workspace
Clearing off the desk and creating a neat workspace sets a tone for
the rest of the day, says Alexandra Levit, the author of Blind Spots:
The 10 Business Myths You Canât Afford to Believe on Your New
Path to Success. 

It can also help avoid confusion. âWhile most communications
are through e-mails and texts, if your boss or co-worker stopped by
looking for you and left a sticky note about a last-minute meeting
occurring in ten minutes, and itâs sitting on a mound of mail
or papers, youâre already behind the eight ball,â
Taylor says. âAlso, for many, itâs difficult to think
clearly, easy to forget important reminders, and just plain stressful
if you feel youâre fighting the battle and the tornado of mail
or paper is winning.â Ideally, youâd clear whatever
you can out the night before so you can have a fresh start before you
even turn on your computer in the morning. But if not, make sure
clearing your desk takes precedence over things like checking e-mails
and chatting with co-workers in the morning.

** Remind yourself of your core purpose at work
âAs corny or as trite as this may sound, Iâd suggest
that you take a moment each morning to remind yourself of your core
purpose at work,â Kerr says. Connecting to a sense of purpose
is one of the most powerful motivators there is, and taking just a
moment each day to reconnect to what truly matters in your job and
what you are ultimately trying to achieve and for whom, can help you
feel more motivated and help you focus on the priority areas in your
work. 

** Donât be distracted by your inbox
This one is difficult for most peopleâbut the experts agree
that you shouldnât check your e-mail first thing in the
morning. If you do, only read and respond to messages that are
urgent. âPriority-scan your inbox,â Taylor
says. âNot all e-mails were created equal. Hone your ability
to quickly sift the wheat from the chaff and address what must be
answered on an urgent basis.â 

Attridge agrees. âOnly respond immediately to the urgent
messages so that you control your morning activities.â There
will be time during the day to respond to the less urgent e-mails.

Why must you put off checking e-mails? âFor far too many
people, e-mail and the web can serve as huge time-wasters and
distracters, particularly in the morning,â Kerr says.

âOnce you start checking e-mails, itâs a click away
from watching the funny video someone forwarded you, which then sucks
you into the abyss: checking the sports scores on line, the news
headlines, the stocks, et cetera, and before you know it
youâve been watching a cat play the drums for twenty minutes
and, like a poorly planned Oscars ceremony, your entire schedule is
already thrown off before youâve even begun your day.â

** Listen to your voice mail
Most people jump on the computer and ignore their
phone. âWhile office voice mail is indeed becoming antiquated
as people rely more on personal cell phones, Blackberrys and e-mail,
some people do leave voice messages, and if you ignore them, you could
miss something important,â Levit says. 

** Place important calls and send urgent e-mails
If you know you need to get in touch with someone that day, place the
call or send the e-mail first thing in the morning. If you wait until
midday, thereâs a greater chance you wonât hear back
before you leave the office. âThereâs nothing more
frustrating that trying to complete something and not having access or
answers from people you need because your day time hours were lost on
other matters,â Taylor says. âIf you have your
questions ready and your e-mails fired off during early peak hours, by
the end of the day you should have what you need.â 

** Take advantage of your cleared mind
âMany people feel that their brains function best in the
morning, and that morning is when they are most creative and
productive,â Kerr says. âConsider whether you are
making the best use of your brainpower and plan âhigh
brainâ activities in the morning.â 

** Mix things up from time to time
Some people like order and are habitualâbut others like
variety and change. âFor them, my advice is to shake things up
occasionally by sitting somewhere different (if you have the choice)
so you get a different perspective; go walkabout first thing and be
visible to people in other spaces, both from a social point of view
and as an alternative to picking up the phone,â Shindler
says. âSmall things that can energize you from the off and can
positively impact you and the office dynamics.â 

** Plan a mid-morning break
âThis is the time to assess where you and take time to
revitalize yourself so that you can keep your momentum going,â
Attridge says. 

If youâre stuck in a routine that doesnât include
these must-dos, it may be worthwhile to re-examine your habits and
make some changes for enhanced career development, Taylor says.

âHabits are created out of having regular cues that prompt a
routine, which then eventually become our habits,â Kerr
adds. The morning is the perfect time to create some critical habits
that will, over time, become routine and help you be more focused and
productive.

âI know my morning routines are critically important. They
help me focus and build momentum,â he
says. âIâm a big believer in thinking about the start
of your day the night before.â

Taylor adds that itâs also helpful not to be too tied to your
routines or rigid plans. âExpect the unexpected, allow
flexibility, and look at the big picture in what your productivity
will look like end of day. Youâre likely to be thrown a
curveâyou might not check off all your initial to-dos. But you
can take pride in your ability to handle the unforeseen.â


* Lunch time at work

How do you spend your lunch break? Do you quickly chow down a sandwich
at a nearby deli with your eyes glued to your Blackberry? Do you
devour a salad at your desk with one hand on your keyboard? Perhaps
you skip lunch altogether because you have âtoo much on your
plate.â

âA common complaint I hear is about lunch time getting
squeezed down to ten minutes, or to nothing at all, with people eating
on the fly or eating while hunched over their computers,â says
Michael Kerr, an international business speaker, author and president
of Humor at Work

Why does this happen? Because America has become such a work-obsessed
society that we tend to shun the notion of taking a break, explains
Michael âDr. Woodyâ Woodward, PhD, organizational
psychologist and author of The YOU Plan. âJust like
professional athletes, we all need the energy from calories for our
minds to function at their best. And we all need a little time to
recharge, too.â

Last month I laid out the 14 things you should do at the start of
every work day and the 14 things you should do at the end of every
work day. I concluded that how you spend the first few and last few
hours in the office can have a significant effect on your level of
productivity. As it turns out, what you do during your lunch hour can
be just as important, and that time shouldnât be
overlooked. Taking a midday break during which you refuel and
re-energize can not only make you a better employee, but also a
healthier and happier person.

âYou should be as strategic about your lunch hour as you are
about your day in general,â says Lynn Taylor, a national
workplace expert and author of Tame Your Terrible Office Tyrant.

With the help of career and workplace experts Michael Kerr, Michael
âDr. Woodyâ Woodward, Lynn Taylor, Anita Attridge,
Alexandra Levit and David Shindler, I compiled a list of 14 things all
workers should do during their lunch break.

âItâs critical to make the most of lunch and remind
yourself that by taking a proper break you will accomplish more in the
long run, and that productivity and creativity will increase, while
your levels of stress and fatigue will diminish,â Kerr says.

Anita Attridge, a career and executive coach with the Five
OâClock Club, a career coaching organization, adds that taking
time to disconnect from your work provides renewed energy, and, as a
result, makes the rest of the day go more
smoothly. âTypically, the afternoon can bring some lulls that
can be offset by having been away from your desk. Talking with people
about something besides work during lunchtime can also boost your
energy level and improve your mood.â

Alexandra Levit, the author of Blind Spots: The 10 Business Myths You
Canât Afford to Believe on Your New Path to Success, agrees. A
lunch break not only fuels your motivation to power toward the end of
the day, it lso gives you something to look forward to in the
morning. âMost people accomplish work best in short bursts
with breaks in between, so organizing your schedule around these
natural energy peaks will help you be more productive.â

What you do during your midday break might vary depending on your job,
company culture or personal prioritiesâbut the experts agree
all workers should try to do these 14 things during lunch hour:

âYou have the ability to make your lunch hour an invigorating
boost to your afternoon by doing what you enjoy; be it a brisk walk
listening to music, talking with a close friend, being in nature, even
if briefly, or spending time on your favorite project or
pastime,â Taylor concludes. âItâs your time to
refresh.â

** Make a plan.
âDonât squander your lunch break because itâs
âfree time,ââ Taylor says. Time is a
non-renewable resource, wherever you are, whatever the time of
day. Try your best to plan it out and make the most of it.

You should also plan your activities immediately after lunch, Kerr
suggests. âGiving thought to how you prioritize and schedule
events in the afternoon can maximize your productivity. For example,
scheduling a meeting or conference call right after lunch may end up
causing you  stress over the lunch hour or you may end up squeezing
the lunch break in order to get back in time and be ready for the
meeting.â

** Take a real break.
Breaking from work for 60 seconds to chow down your lunch at your desk
doesnât count. âIn order to get a period of true
respite, the time has to involve an actual break from work,â
Levit says. Try not to check your e-mail, bring work with you or talk
about work during lunch.

** Get up from your desk or work space.
âStaying at your desk is a big no-no in my book,â Kerr
says. âThere are more and more reports on the dangers of
sitting too long, so even just getting up to walk to another room to
eat is important, or better still, getting outside for some fresh air
and a quick walk can do wonders for the body and spirit.â

Even if you donât sit at a desk, you should get away from your
work space during lunch, as it will help you clear your mind.

** Eat.

Donât try to be a hero and starve yourself for the sake of
being a hard worker or checking off another âto-doâ
item, Taylor says. âYouâll pay for it later when you
canât concentrate and throw your body off balance. If
youâve earned a headache or are lightheaded at 4 p.m., you
havenât ultimately gained anything.â

** Enjoy your food

Lunch should be about having lunch, Woodward says. âTreat
yourself to something you enjoy that fits with your diet,â he
adds. âIf you have a favorite place or a particular food you
enjoy make sure to go and enjoy it at least once a week. You only live
once.â

Itâs OK to splurge from time to timeâbut try to stick
to healthy meals as often as possible.


** Do what you canât do in the morning or evening.

Some errandsâlike going to the Post Office or the
bankâmust be handled during work hours. âBe strategic
and use your lunch break to accomplish some of those personal errands
that canât be handled before or after work, or on the
weekends,â Taylor says.

But be careful that you donât cram too many personal errands
into your lunch break, Kerr warns. âYouâd just end up
swapping one stress for another kind of stress without getting the
re-energizing benefits a good break can offer.â

** Use the time to connect with someone new.

âI used to work in an office of 3,000 people, so it was pretty
much the norm to not recognize most everyone in the elevator,â
Woodward says. âOur workplace interactions can be so fleeting
that we really never actually get to know the people we spend most of
our days with. When you donât really know those you interact
with itâs easy to dehumanize them and take them for
granted. Take some time to get out of the office, grab a sit down
lunch, and get to know your co-workers.â

** Catch up with old friends.

If you have a friend who works nearby, try to meet him or her during
lunch occasionally. âRemember, your personal life needs
tending to just as much as your work-life, so be sure to take the
spare time you have and use it to fulfill your personal
needs,â Woodward says. Your midday break is a good opportunity
to catch up and socialize, in person or by phoneâbut
donât lose track of time, and donât treat it like
happy hour.

** Have a system for dealing with your absence.

This will allow people inside and outside the company to know when you
will be back, how to contact you in an emergency or have an
alternative point of contact, says David Shindler, author of Learning
to Leap and founder of social learning site, The Employability Hub. It
may also help you relax and avoid obsessively checking your e-mail
during lunch.

** Engage in activities that will help you re-energize.

Take a walk outside, visit the gym or meditate. Get out and do
something that will make you feel better about yourself. âA
quick dose of sunlight and fresh air is the perfect elixir for the
midday blues,â Woodward says.

** Network.

Even if youâre perfectly happy in your job, and youâre
not looking for a new one, it canât hurt to continuously build
and maintain your professional network. âThis is critical to
success in any line of work,â Woodward says. âHowever,
finding the time to connect with those in your network can be
tough.â

Attridge adds, âStrategically, lunch is an excellent time to
continue to build relationships and network with others whether that
is by having lunch with them or calling them to catch up.â

** Donât get stuck in a routine.

Many of us are creatures of habit. Maybe you go to the same pizzeria
everyday or eat with the same colleague. You might always use your
lunch break to run errands or make personal calls. Try to mix things
up in order to clear your head and boost your energy.

** Avoid all screens.

Try to stay away from your iPhone, iPad, Blackberry and
computer. âGive your eyes a break,â Taylor says. Most
office jobs require you to stare at a screen all dayâso try to
avoid that during lunch.

If you canât help it for whatever reason (maybe you want to
shop online or e-mail a friend), get up from your desk so your body
perceives this as a true break, Levit adds.

** Donât take too long or too short of a break.

If youâre allotted an hour for lunch, take it. Maybe not every
day, but when you can, use the full sixty minutes to get out, eat,
exercise your mind or body, catch up with an old friend or a colleague
and/or tackle items on your personal agenda.

However, if everyone else in the office takes shorter breaks, follow
suit so you donât stand out.

âDonât take breaks that are too long or too frequent,
as people will start to notice,â Levit says. âAnd
donât pressure colleagues to adhere to your break
schedule. You are primarily there to workânot
socializeâso let them do what works best for them.â

* End of the workday routine

âHow you end the day is critical, as it has much to do with
how you start the next day,â says Lynn Taylor, a national
workplace expert and author of Tame Your Terrible Office Tyrant; How
to Manage Childish Boss Behavior and Thrive in Your Job. Itâs
half of the puzzle of being productive. Both pieces are like bookends
that carry extra weight relative to what happens in
between. Theyâre like first and last impressions that hold
tremendous impact on your view of your work, attitude and productivity
level. The end of your day sets the stage for tomorrow, and the start
of your day sets the stage for today.â

Ending your day on a good note will also ensure that you look back on
it with a sense of accomplishment and fulfillment, making it easier to
get up and go to work the next morning, adds Alexandra Levit, the
author of Blind Spots: The 10 Business Myths You Canât Afford
to Believe on Your New Path to Success.

Another reason to end your day the right way: Michael Kerr, an
international business speaker, author and president of Humor at Work,
says it has a huge effect on the level of stress and happiness you
carry home, âwhich in turn can impact your health, your
marriage and family life, your ability to sleep and your overall level
of happiness.â

With the help of career and workplace experts Lynn Taylor, David
Shindler, Michael Kerr, Anita Attridge, Alexandra Levit and Michael
âDr. Woodyâ Woodward, I compiled a list of 14 things
all workers should do at the end of every work day.

âJust as itâs never a good idea to hard crash your
computer, you shouldnât hard crash your day,â advises
Michael âDr. Woodyâ Woodward, PhD, organizational
psychologist and author of The YOU Plan. âClosing out your day
in an orderly and positive way is critical to making that clean
psychological transition into the personal side of life.

Nobody likes that feeling of unfinished business hanging over their
head while playing with the kids or dining with the family, so
itâs important that you do what you can to make as clean a
break as possible when walking out the office door.â

** Evaluate your to-do list
Make sure you are where you need to be on these activities and that
youâve accomplished as much as you could, says Anita Attridge,
a career and executive coach with the Five OâClock Club, a
career coaching organization. âIf you arenât satisfied
with where you are, plan what you need to do and when you will do it
so you donât get further behind.â If you could quickly
get something done before you leave, do it. This will save you time
the next morning. 

** Review your schedule for the next day
Make sure youâre aware of any meetings or calls for the
following day. You can also use this opportunity to schedule time on
your calendar to accomplish any remaining items from todayâs
to-do list.

âSome people like to visualize, make a mental or physical note
of what is on their schedule first thing the next day,â says
David Shindler, founder of The Employability Hub and author of
Learning to Leap. âThink about one thing you are most looking
forward to tomorrow. It will help you leave behind whatâs
happened today, enrich your current mood and help to put a full stop
to your working day.â

** Check in with your boss and colleagues.
Depending on how hands-on your boss is, you may want to visit with him
or her to discuss the status of any projects youâre working
on, Taylor suggests. Youâll also want to get end-of-day
updates from co-workers.

This is also a great opportunity to double-check deadlines and confirm
that everyone is on the same page.

** Tidy up
Nobody likes the feeling of walking into a mess, especially when you
are under the gun, Woodward says.  Before walking out the door take a
few minutes to toss any trash, organize your paperwork and straighten
up your desk. This will give that feeling of a fresh start when you
arrive the next morning. 

You should also clean out your in-box. âBlock off at least 15
minutes at the end of your day to sort through those unnecessary CCs,
happy hour invitations, and random solicitations,â he
says. âE-mails can stack-up fast and itâs easy to miss
those critical ones when your in-box gets too backed-up.â

** Complete non-peak hour work
The end of the day is the best time to handle paperwork and tasks that
donât require phone contact. âE-mails, reports, status
memos and thinking projects are best handled when phone calls, texts
and other distractions have subsided,â Taylor says. Hopefully,
youâve maximized the peak hours to contact the people you need
so that you can complete the administrative side of your job armed
with their input. The end of the day is the time to determine who you
need to reach first thing in the morning. 

** Get closure
Be sure to tie up any loose ends so that you can truly disconnect when
you walk out the door, Woodward says. Be sure not to leave anything
hanging that can quickly be taken care of. âThere is nothing
worse than having that feeling of something hanging over your
head,â he says. Attridge agrees. She suggests you take a few
minutes to send that e-mail youâve been meaning to send,
respond to that request that you can quickly answer, or touch base
with a colleague you been meaning to see. 

** Make a new to-do list
Determine what you must accomplish the next day and have a plan of how
you will use your time to manage your priorities, Attridge
says. Youâll probably update or expand your to-do list the
following morning, but it doesnât hurt to compile a
preliminary list the night before. 

âBased on the dayâs events and input, reflect those
changes on your master to-do list so that when you start your day,
youâre that much further ahead of the game,â Taylor
says. âAnything you can do to have a head start in the morning
will help you achieve more productive days and a more productive
career.â

** Reflect on the day
Unfortunately most people donât do this. Theyâll run
out the door the second theyâre done with their work. But if
you can make time to reflect on your best achievement or success that
day, you could end up walking out with a spring in your step, Shindler
says. 

** Write down your accomplishments
âHappiness researchers suggest that writing down three
positive things that happened during our day is one of the most
effective ways to boost long term happiness levels,â Kerr
says. âItâs not enough to simply reflect, you need to
put them down on paper. The end of the work day is a perfect time to
do this.â 

** Say good bye
Kerr says itâs important to create routines and rituals at
work that will helps us feel more fulfilled and happy in the long run,
âso that we go home feeling reenergized and inspired, instead
of fried and dead tired.â One simple routine that falls into
this category is saying a proper good bye to your
colleagues. âWe tend to think about the importance of checking
in and saying good morning to kick off the day, but we forget that it
can be just as important, and make us feel good as well, to say a
friendly and proper good bye to everyone rather than just silently
drift off into the night. This is triply important if you are the
supervisor.â 

** Resist last minute, low priority e-mail and calls
As you prepare to head home, try not to be drawn in by last minute,
non-essential emails or calls, Taylor says. âDespite your best
intentions to start the next morning with a clean slate, you may get
mired into a long-winded late day project or dialog of low
priority. Just because they appeared after you cleared your Inbox at
6pm, doesnât make them more urgent. Consider that these late
emails may be arriving because others know youâre finally
undistracted; they may finally be getting to their own non-peak hour
work; or they may seek greater recognition working long
hours.â 

** Leave on a positive note
Take note of something that went well, compliment a co-worker on an
accomplishment, or drop a thank you note to a client, Woodward
says. âThe idea is to find something positive that makes you
feel good about your job and make sure that moment is the last thing
on your mind before walking out the door.â 

Taylor agrees. âIf you have people reporting to you, say a few
words of encouragement before you head for the door,â she
says. âMost workers want to feel appreciated and know
theyâre making a difference in the big picture.â

** Disconnect
Donât be afraid to shut down your smartphone or at least shut
off the e-mail alerts, Woodward says. Let people know about it. When
you walk out that door be sure to tell your colleagues the period of
time you will be unavailable and stick to it. âItâs
important to be present for your family and friends,â he
says. 

** Have a plan for your commute home
Commuting is a huge source of stress for people, but if you create a
plan to either use the time more efficiently (such as learning a new
language on the train) or make it less stressful by listening to your
favorite comedy or speaker podcasts on the drive home, you can look
forward to the commute rather than dread it, Kerr
says. âPlanning a different mental activity also builds in a
buffer between your work and personal life.â 

** Leave your stress at the door
When you walk out that door commit to leaving your stress
behind. âLeaving the office at the end of the day can be
tough, but carrying your stress home with you wonât serve any
good,â Woodward says. âYour family needs you to be
present, so do what you can to make sure your stress stays at the
office.â 

** Go home
Turn off your lights and equipment, and go home, Levit suggests.

Donât aim to be the last to leave for the sake of face time,
Taylor adds. Youâll wear yourself out and your productivity
will slip. Itâs one thing to be a hard worker, another to hang
around for Brownie points, achieving nothing. Better to plan for the
next day, get rest and be clear-headed in the morning. âIf
more than one person has labeled you a âworkaholicâ or
youâve forgotten the name of your pet golden retriever, it may
be time to do â80%â and not give 110%,â Taylor
says. âThen you may normalize your work patterns more
effectively.â

Shindler adds:  âDonât stay just to keep up with the
boss. Donât leave just because you can.  Your colleagues may
depend on you. Do the right things and do things right.â

* Successful Leadership
 Leadership is learned behavior that becomes unconscious and automatic over
 time.  For example, leaders can make several important decisions
 about an issue in the time it takes others to understand the
 question.   Many people wonder how leaders know how to make the best
 decisions, often under immense pressure.  The process of making these
 decisions comes from an accumulation of experiences and encounters
 with a multitude of difference circumstances, personality types and
 unforeseen failures.   More so, the decision making process is an
 acute understanding of being familiar with the cause and effect of
 behavioral and circumstantial patterns;  knowing the intelligence and
 interconnection points of the variables involved in these patterns
 allows a leader to confidently make decisions and project the
 probability of their desired outcomes.   The most successful leaders
 are instinctual decision makers.  Having done it so many times
 throughout their careers, they become immune to the pressure
 associated with decision making and extremely intuitive about the
 process of making the most strategic and best decisions. This is why
 most senior executives will tell you they depend strongly upon their
 âgut-feelâ when making difficult decisions at a
 momentâs notice.

Beyond decision making, successful leadership across all areas becomes
learned and instinctual over a period of time. Successful leaders have
learned the mastery of anticipating business patterns, finding
opportunities in pressure situations, serving the people they lead and
overcoming hardships.   No wonder the best CEOs are paid so much
money.   In 2011, salaries for the 200 top-paid CEOs rose 5 percent to
a median $14.5 million per year, according to a study by
compensation-data company Equilar for The New York Times.

If you are looking to advance your career into a leadership capacity
and / or already assume leadership responsibilities â here are
15 things you must do automatically, every day, to be a successful
leader in the workplace:

** Make Others Feel Safe to Speak-Up

Many times leaders intimidate their colleagues with their title and
power when they walk into a room.   Successful leaders deflect
attention away from themselves and encourage others to voice their
opinions.  They are experts at making others feel safe to speak-up and
confidently share their perspectives and points of view.   They use
their executive presence to create an approachable environment.

** Make Decisions

Successful leaders are expert decision makers.    They either
facilitate the dialogue to empower their colleagues to reach a
strategic conclusion or they do it themselves.  They focus on
âmaking things happenâ at all times â decision
making activities that sustain progress.   Successful leaders have
mastered the art of politicking and thus donât waste their
time on issues that disrupt momentum.  They know how to make 30
decisions in 30 minutes.

** Communicate Expectations

Successful leaders are great communicators, and this is especially
true when it comes to âperformance expectations.â   In
doing so, they remind their colleagues of the organizationâs
core values and mission statement â ensuring that their vision
is properly translated and actionable objectives are properly
executed.

I had a boss that managed the team by reminding us of the expectations
that she had of the group.   She made it easy for the team to stay
focused and on track.  The protocol she implemented â by
clearly communicating expectations â increased performance and
helped to identify those on the team that could not keep up with the
standards she expected from us.

** Challenge People to Think

The most successful leaders understand their colleaguesâ
mindsets, capabilities and areas for improvement.  They use this
knowledge/insight to challenge their teams to think and stretch them
to reach for more.   These types of leaders excel in keeping their
people on their toes, never allowing them to get comfortable and
enabling them with the tools to grow.

If you are not thinking, youâre not learning new things.  If
youâre not learning, youâre not growing â and
over time becoming irrelevant in your work.

** Be Accountable to Others

Successful leaders allow their colleagues to manage them.  This
doesnât mean they are allowing others to control them
â but rather becoming accountable to assure they are being
proactive to their colleagues needs.

Beyond just mentoring and sponsoring selected employees, being
accountable to others is a sign that your leader is focused more on
your success than just their own.

** Lead by Example

Leading by example sounds easy, but few leaders are consistent with
this one.   Successful leaders practice what they preach and are
mindful of their actions. They know everyone is watching them and
therefore are incredibly intuitive about detecting those who are
observing their every move, waiting to detect a performance shortfall.

** Measure & Reward Performance

Great leaders always have a strong âpulseâ on business
performance and those people who are the performance champions. Not
only do they review the numbers and measure performance ROI, they are
active in acknowledging hard work and efforts (no matter the result).
Successful leaders never take consistent performers for granted and
are mindful of rewarding them.

** Provide Continuous Feedback

Employees want their leaders to know that they are paying attention to
them and they appreciate any insights along the way.  Successful
leaders always provide feedback and they welcome reciprocal feedback
by creating trustworthy relationships with their colleagues..   They
understand the power of perspective and have learned the importance of
feedback early on in their career as it has served them to enable
workplace advancement.

** Properly Allocate and Deploy Talent

Successful leaders know their talent pool and how to use it.  They are
experts at activating the capabilities of their colleagues and knowing
when to deploy their unique skill sets given the circumstances at
hand.

** Ask Questions, Seek Counsel

Successful leaders ask questions and seek counsel all the time.  From
the outside, they appear to know-it-all â yet on the inside,
they have a deep thirst for knowledge and constantly are on the
look-out to learn new things because of their commitment to making
themselves better through the wisdom of others.

** Problem Solve; Avoid Procrastination

Successful leaders tackle issues head-on and know how to discover the
heart of the matter at hand.    They donât procrastinate and
thus become incredibly proficient at problem solving; they learn from
and donât avoid uncomfortable circumstances (they welcome
them).

Getting ahead in life is about doing the things that most people
donât like doing.

** Positive Energy & Attitude

Successful leaders create a positive and inspiring workplace culture.
They know how to set the tone and bring an attitude that motivates
their colleagues to take action.   As such, they are likeable,
respected and strong willed.  They donât allow failures to
disrupt momentum.

** Be a Great Teacher

Many employees in the workplace will tell you that their leaders have
stopped being teachers.   Successful leaders never stop teaching
because they are so self-motivated to learn themselves.  They use
teaching to keep their colleagues well-informed and knowledgeable
through statistics, trends, and other newsworthy items.

Successful leaders take the time to mentor their colleagues and make
the investment to sponsor those who have proven they are able and
eager to advance.

** Invest in Relationships

Successful leaders donât focus on protecting their domain
â instead they expand it by investing in mutually beneficial
relationships. Successful leaders associate themselves with
âlifters and other leadersâ â the types of
people that can broaden their sphere of influence.  Not only for their
own advancement, but that of others.

Leaders share the harvest of their success to help build momentum for
those around them.

** Genuinely Enjoy Responsibilities

Successful leaders love being leaders â not for the sake of
power but for the meaningful and purposeful impact they can create.
When you have reached a senior level of leadership â
itâs about your ability to serve others and this canât
be accomplished unless you genuinely enjoy what you do.

In the end, successful leaders are able to sustain their success
because these 15 things ultimately allow them to increase the value of
their organizationâs brand â while at the same time
minimize the operating risk profile.   They serve as the enablers of
talent, culture and results.

* How to make a habit

On a daily basis, habit drives us to do what we doâwhether
itâs a pattern of thoughts or behavior that occurs
automatically. But what if we could harness the power of our habits
for the better? Imagine a life where you have a habit of completing
projects, eating well, keeping in touch with family and friends, and
working to your fullest potential. When you have a foundation of good
habits, youâre setting yourself up for a full, healthy, and
successful life.

Iâve used these principles to establish the lifestyle I have
nowâas a fitness expert, author, public speaker, owner of a
fitness studio and a fitness lifestyle company, and as a wife and
mother. If I hadnât established positive habits, I
couldnât do half of these things, at least not with my sanity
intact! Here are 7 steps to changing your habits that will, in turn,
change your entire life.

** Identify your Keystone Habit, and focus on it.

In one of my favorite books, The Power of Habit, Charles Duhigg
outlines the importance of identifying your Keystone Habitâthe
habit you identify as the most important thing you can change about
your life. To find out what that is for you, ask yourself, what
constantly gnaws at you? Is it something you do that you want to stop,
or something you donât do and want to start? The keystone
habit is different for everyone, and it may take a few sessions of
deep thinking to pinpoint exactly what that habit is. Whichever habit
youâre working on, pick one at a time. More than one at a time
will be overwhelming and will increase your likelihood of failing to
improve any habits. But donât believe you can only change one
thing about yourself; itâs actually the opposite. Working on
this one Keystone Habit can have a positive ripple effect into the
rest of your life as well.

** Identify your current routine and the reward you get from it.

Letâs say you want to build a habit of getting to the office a
half hour early each day. You want to do this because you think the
extra quiet time in the morning will help you to be more productive,
and that productivity will be rewarded by an increased sense of job
satisfaction, and an overall better work environment. Currently, you
get to the office just on time. Your current routine is to leave your
house in a rush, at the exact time youâve calculated that
(without traffic or incident) will get you to work on time. Your
reward is spending some extra time at your house in the morning,
spending an extra half hour sleeping or âcharging your
batteriesâ for the day ahead.

** Consider the challenges.

Challenges are often cues that push you to fall back into old
habits. In the example of getting to work earlier, your challenges may
lie in your sleep patterns the night before, or in coordinating
schedules with a partner. These challenges will not magically
disappear so you need to take them into account. But donât let
the presence of challenges, or worry that new challenges will come up
in the future, deter you from establishing your new habits. If your
challenges include coordinating with other people, make them a part of
your new routine, as Iâll explain later. Right now, simply
identify what the challenges or obstacles are.

** Plan your new routine and pinpoint the reward.

Old habits never disappear; they are simply replaced with new
habits. In the example of getting to the office earlier, the new
routine involves leaving the house a half hour earlier. If the old
habit was rewarded with the thought that youâll have more
energy for the day by staying in your house longer, the new habit
needs to focus around the idea that more rest doesnât
necessarily mean more energy. In other words, youâll want to
address what you think youâll be giving up by replacing the
old habit.

** Set up a 30-day challenge.

In most cases, our failure to curate good habits simply comes from not
sticking to them. Plenty of studies show that habits, when performed
daily, can become part of your routine in as  little as 21 days. So
set a start date and launch your plan of action for a trial 30-day
period.

** Power through setbacks.

Sometimes, itâs not just willpower that runs out. Sometimes we
are swayed from our paths by life âgetting in the wayâ
of new goals. If something sways you from your challenge, the best
course of action is to evaluate the situation and see how you can get
around, over, or through that obstacle. However, once a new habit is
established, it actually becomes our default setting. If your usual
habits are healthy, then stressful times are less likely to throw you
off from your usual routines. In other words, weâre just as
likely to default to healthy habits as we are to self-sabotaging
habits, if those healthy habits have become a part of our everyday
routine.

** Hold yourself publicly accountable.

Your support network is the most valuable tool you will ever have
access to. Whether itâs your best friend, your partner or your
Facebook posts, being accountable to someone other than yourself will
help you stick to your goal. Just keep in mind that
âaccountableâ isnât the same as
âannouncementâ. Anyone can tell the world
theyâre going to get up early from now on. But, if that person
has a team of supporters behind them, whom they regularly update, they
are more likely to stick with their new habit during times when they
are establishing their new habit and motivation is running low.



* Blog details
** Copyright

Copyright © 2013  [[mailto:mehul@sanghvi.org][Mehul Sanghvi]]. Published under the terms of the
[[http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US][Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License]].

** About

Being productive, boosting moods, improving routines.

* Changelog

- 2013-10-24
  - Initial creation
- 2015-08-16
  - Organised headings and sub-headings properly
